### ISSUE TITLE
Add module for IR analyses

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/llhd#108]
Various analysis passes on the IR currently live in whatever `pass` they were initially needed for. These should rather go in a separate `analyses` module, either under `ir` or the crate root. It would also be beneficial for the `UnitData` to maintain these analyses in an on-demand manner, with `Unit` computing them on access, and `UnitBuilder` invalidating them.

## Todo
- [x] Factor out `TemporalRegionGraph` from `tcm`
- [x] Factor out `PredecessorTable` from `gcse`
- [x] Factor out `DominatorTree` from `gcse`
- [x] Add accessors for the above to `Unit` and `UnitBuilder`
