### ISSUE TITLE
Apply changes to arith/drv/reg instruction specs to codebase

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/llhd#115]
There have been some spec changes to arithmetic instructions, as well as the `drv` and `reg` instructions. Apply these to the codebase, more specifically in the `ir`, `verifier`, and `assembly` modules.

## Todo
- [ ] Merge `smul` and `umul`
- [ ] Remove `smod`
- [ ] Adjust syntax of `drv`
- [ ] Add `after` option/necessary field to `reg`
