### ISSUE TITLE
Add dynamic extract instructions

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/llhd#139]
Add the `dextf` and `dexts` instructions, which are equivalent to `extf` and `exts` in their operation, except that the base offset can be an SSA value rather than an constant immediate. This will then replace combinations of `shr`+`extf` and `shr`+`exts`.

## Todo
- [ ] Add instruction implementations and add parsing roundtrip tests
- [ ] Implement constant folding and add tests
- [ ] Implement simulation and add tests
