### ISSUE TITLE
Require prb/drv in entities

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/llhd#52]
For now, require entities to use `prb`/`drv` instructions to interact with signals. The entities retain their data flow behaviour, but the change allows for zero-time computation to occur on values. This means that code will look a bit redundant and ugly, since especially small transfer functions on signals will read to a lot of `prb` noise, but the semantics are much more clear and the IR becomes easier to construct and check.

### Todo
- [x] Allow `prb` and `drv` in entities
- [x] Remove code that automatically wraps entity instruction types in a signal
- [x] Remove code that tries to be signal-transparent (e.g. `add` on signals is no longer allowed/needed)

**Comment by fabianschuiki** [comment]
Implemented in 1afbd1b.
