### ISSUE TITLE
Make `Unit` object safe

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/llhd#65]
Make the `Unit` trait object safe. Currently this is not the case, since `dump()` refers to the `Self` type. If we were able to omit that, then `Unit` could be used as a trait object as well. This is pretty handy in user code, if full polymorphism is not desired.

### Todo
- [ ] Adjust `dump()` to make `Unit` object safe
- [ ] Add new helper functions to `Module`:
    - [ ] `get_function()`
    - [ ] `get_process()`
    - [ ] `get_entity()`
    - [ ] `get_function_mut()`
    - [ ] `get_process_mut()`
    - [ ] `get_entity_mut()`
