### ISSUE TITLE
Preserve labels and numbers during assembly reading

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/llhd#69]
Preserve the anonymous names used in an assembly file. Currently anonymous names (e.g. `%42`) are only used to look up other values, but are then discarded. There should be a name hint in the DFG that allows these numbers to be preserved. When dumping/formatting instructions, these hints should then be used to make it easy for the user to associated the two.

### Todo
- [x] Preserve anonymous names in the parser as name hints in the DFG
- [x] Extend the instruction/value dumper to use names for values as far as possible
- [x] ~~Consider using the assembly writer to dump instructions~~

**Comment by fabianschuiki** [comment]
Implemented in c045e306.
