### ISSUE TITLE
Track aliases in TCM

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/llhd#98]
Improve the Temporal Code Motion pass by tracking signal aliases and leveraging conditional drives (#97).

## Todo

- [x] Add a mapping of alias signals to their original signal (populate upon `extf/exts/shl/shr`).
- [x] When moving `drv` down, add branch conditions as drive condition (see graph-ir branch).
- [x] Coalesce drives to the same signal: build discriminator table among drive conditions, build mux to select based on discriminator, use or of all drive conditions as new drive condition.

## Example
```
proc @foo (i1 %A) -> (i8$ %D) {
entry:
    %D0 = exts i4$, i8$ %D, 0, 4
    drv i8$ %D, 0, 1d
    br %A, %wayA, %wayB
wayA:
    drv i4$ %D0, 7, 1d
    br %final
wayB:
    drv i4$ %D0, 15, 1d
    br %final
final:
    wait %entry, %A
}
```
Move drives down:
```
proc @foo (i1 %A) -> (i8$ %D) {
entry:
    %D0 = exts i4$, i8$ %D, 0, 4
    br %A, %wayA, %wayB
wayA:
    br %final
wayB:
    br %final
final:
    drv i8$ %D, 0, 1d
    %nA = not i1 %A
    drv i4$ %D0 if %nA, 7, 1d
    drv i4$ %D0 if %A, 15, 1d
    wait %entry, %A
}
```
Coalesce drives and eliminate trivial BBs:
```
proc @foo (i1 %A) -> (i8$ %D) {
entry:
    %D0 = exts i4$, i8$ %D, 0, 4
    br %final
final:
    drv i8$ %D, 0, 1d
    %v = mux [i4 7, 15], i1 %A
    drv i4$ %D0, %v, 1d
    wait %entry, %A
}
```
Coalesce aliased drives:
```
proc @foo (i1 %A) -> (i8$ %D) {
entry:
    %0 = const i8 0
    %v = mux [i4 7, 15], i1 %A
    %1 = inss i8 %0, i4 %v, 0, 4
    drv i8$ %D, %1, 1d
    wait %entry, %A
}
```

**Comment by fabianschuiki** [comment]
Rather than eagerly inserting drives, consider building a list of them, then pre-process this list to find drives with the same value but different conditions (to collapse), drives with different values and the same condition (last one wins), and drives with different values and conditions (to find the value discriminator and collapse them).

**Comment by fabianschuiki** [comment]
An issue at the moment is the fact that for drive coalescing to work optimally, common subexprs must have been eliminated. This means that either GCSE needs to run between moving `drv`s and coalescing them, or that TCM needs to perform CSE on-the-fly as it inserts new instructions.
